all:
  children:
    primary:
      hosts:
        uds-server01:
          ansible_host: 103.131.85.183
          keepalived_priority: 101
          keepalived_state: MASTER
          mysql_server_id: 1
          mysql_role: primary
          galera_bootstrap_node: true
    secondary:
      hosts:
        uds-server02:
          ansible_host: 103.131.85.163
          keepalived_priority: 100
          keepalived_state: BACKUP
          mysql_server_id: 2
          mysql_role: replica
          galera_bootstrap_node: false
    uds_servers:
      children:
        primary:
        secondary:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: /home/phongnva/Desktop/PhongNVA/openuds/server/deployment/Ansible/phongnva
    ansible_python_interpreter: /usr/bin/python3
