all:
  vars:
    ansible_user: root
    ansible_become: true
  children:
    primary:
      hosts:
        uds-dev01:
          ansible_host: 192.0.2.11
          keepalived_priority: 101
          keepalived_state: MASTER
          mysql_server_id: 1
          mysql_role: primary
          galera_bootstrap: true
    secondary:
      hosts:
        uds-dev02:
          ansible_host: 192.0.2.12
          keepalived_priority: 100
          keepalived_state: BACKUP
          mysql_server_id: 2
          mysql_role: replica
    uds_servers:
      children:
        primary:
        secondary:
    load_balancers:
      children:
        primary:
        secondary:
    web_servers:
      children:
        primary:
        secondary:
    app_servers:
      children:
        primary:
        secondary:
    db_servers:
      children:
        primary:
        secondary:
