---
- name: Check wsrep_cluster_size
  command: >-
    {{ galera_mysql_cli }} -Nse "SHOW STATUS LIKE 'wsrep_cluster_size';"
  register: galera_cluster_size_status
  changed_when: false

- name: Check wsrep_local_state_comment
  command: >-
    {{ galera_mysql_cli }} -Nse "SHOW STATUS LIKE 'wsrep_local_state_comment';"
  register: galera_local_state_status
  changed_when: false

- name: Display Galera status summary
  debug:
    msg:
      - "{{ galera_cluster_size_status.stdout }}"
      - "{{ galera_local_state_status.stdout }}"
