---
- name: Deploy MySQL config
  template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: "0644"
  notify: restart mysql

- name: Apply MySQL config changes immediately
  meta: flush_handlers

- name: Set root password
  mysql_user:
    name: root
    host: localhost
    password: "{{ db_root_password }}"
    login_user: root
    login_password: "{{ db_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
  no_log: true
  ignore_errors: true

- name: Dynamically transition GTID mode ON
  shell: |
    mysql -u root -p"{{ db_root_password }}" -e "
    SET @@GLOBAL.ENFORCE_GTID_CONSISTENCY = WARN;
    SET @@GLOBAL.ENFORCE_GTID_CONSISTENCY = ON;
    SET @@GLOBAL.GTID_MODE = OFF_PERMISSIVE;
    SET @@GLOBAL.GTID_MODE = ON_PERMISSIVE;
    SET @@GLOBAL.GTID_MODE = ON;
    "
  ignore_errors: true
