---
- name: Install MySQL 8.0
  apt:
    name:
      - mysql-server-8.0
      - mysql-client-8.0
      - python3-mysqldb
      - python3-pymysql
    state: present

- name: Start and enable MySQL
  systemd:
    name: mysql
    state: started
    enabled: yes
