---
- name: Install MariaDB + Galera
  apt:
    name:
      - mariadb-server
      - mariadb-client
      - galera-4
      - rsync
      - socat
      - python3-mysqldb
      - python3-pymysql
    state: present

- name: Ensure MariaDB service is enabled
  systemd:
    name: "{{ mysql_service_name }}"
    enabled: yes
