---
- name: Create application database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: root
    login_password: "{{ db_root_password }}"

- name: Create application user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    host: "%"
    priv: "{{ db_name }}.*:ALL"
    login_user: root
    login_password: "{{ db_root_password }}"
    state: present
  no_log: true

- name: Create SST user for Galera mariabackup
  mysql_user:
    name: "{{ galera_sst_user }}"
    password: "{{ galera_sst_password }}"
    host: "localhost"
    priv: "*.*:RELOAD,PROCESS,LOCK TABLES,REPLICATION CLIENT"
    login_user: root
    login_password: "{{ db_root_password }}"
    state: present
  no_log: true

- name: Create HAProxy health-check user (no password)
  mysql_user:
    name: "{{ haproxy_mysql_check_user }}"
    host: "%"
    priv: "*.*:USAGE"
    login_user: root
    login_password: "{{ db_root_password }}"
    state: present

- name: Create replication user
  mysql_user:
    name: "{{ mysql_repl_user }}"
    password: "{{ mysql_repl_password }}"
    host: "%"
    priv: "*.*:REPLICATION SLAVE,REPLICATION CLIENT"
    login_user: root
    login_password: "{{ db_root_password }}"
    state: present
  no_log: true
