---
- name: Create application database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: root
    login_password: "{{ db_root_password }}"

- name: Create application user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    host: "%"
    priv: "{{ db_name }}.*:ALL"
    login_user: root
    login_password: "{{ db_root_password }}"
    state: present
  no_log: true

- name: Create Galera SST user
  mysql_user:
    name: "{{ galera_sst_user }}"
    password: "{{ galera_sst_password }}"
    host: "%"
    priv: "*.*:RELOAD,LOCK TABLES,PROCESS,REPLICATION CLIENT"
    login_user: root
    login_password: "{{ db_root_password }}"
    state: present
  no_log: true
