all:
  children:
    tunnel_servers:
      hosts:
        uds-tunnel01:
          ansible_host: 103.131.85.186
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: /home/phongnva/Desktop/PhongNVA/openuds/server/deployment/Ansible/phongnva
    ansible_python_interpreter: /usr/bin/python3
