upstream uds_server {
    server unix:/run/openuds/socket fail_timeout=10s;
}

map $http_x_forwarded_proto $thescheme {
    default $scheme;
    https https;
}

server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name _;

    ssl_certificate /app/certs/example.com.crt;
    ssl_certificate_key /app/certs/example.com.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_session_timeout 10m;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;
    
    add_header Cache-Control "no-store" always;
    add_header Content-Security-Policy "default-src 'self'; upgrade-insecure-requests; block-all-mixed-content; connect-src 'self'; img-src 'self' data:; frame-ancestors 'self'; form-action 'self'; font-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; script-src-elem 'self' 'unsafe-inline'; object-src 'none'; base-uri 'self';" always;
    add_header Permissions-Policy "geolocation=(self)" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Cross-Origin-Embedder-Policy "require-corp" always;
    add_header Cross-Origin-Opener-Policy "same-origin" always;
    add_header Cross-Origin-Resource-Policy "same-origin" always;
    add_header Access-Control-Allow-Credentials "true" always;
    add_header Access-Control-Allow-Origin "https://trusted-domain.com" always;

    access_log /var/log/nginx/uds_access.log;
    error_log /var/log/nginx/uds_error.log;

    root /app/src;

    # Activate GZIP - saves around 80% of traffic
    gzip on;
    gzip_proxied any;
    gzip_types
        text/css
        text/javascript
        text/xml
        text/plain
        application/javascript
        application/x-javascript
        application/json;

    location /favicon.ico {
        alias /app/src/uds/static/modern/img/favicon.ico;
    }

    location /uds/res/ {
        autoindex off;
        alias /app/src/static/;
    }

    location / {
        proxy_intercept_errors on;
        try_files $uri @proxy_to_uds;
    }
    
    location @proxy_to_uds {
        proxy_hide_header Content-Security-Policy;
        proxy_hide_header X-Frame-Options;
        proxy_hide_header X-XSS-Protection;
        proxy_hide_header X-Content-Type-Options;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $thescheme;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_redirect off;
        proxy_pass http://uds_server;
    }
}
