# -*- coding: utf-8 -*-
"""
Django settings for OpenUDS Docker deployment.
Imports base settings from settings.py.sample and overrides
database, cache, and other configs using environment variables.
"""
import os
import sys

# First, copy settings.py.sample to settings.py if it doesn't exist
# This is handled by entrypoint.sh, but we import from the sample directly
# by loading the base settings file
_base_dir = os.path.dirname(os.path.abspath(__file__))
_settings_file = os.path.join(_base_dir, 'settings.py')
_sample_file = os.path.join(_base_dir, 'settings.py.sample')

# If settings.py doesn't exist, create it from sample
if not os.path.exists(_settings_file) and os.path.exists(_sample_file):
    import shutil
    shutil.copy2(_sample_file, _settings_file)

# Import everything from the base settings
from server.settings import *  # noqa: F401, F403

# Override with Docker-specific settings
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

SECRET_KEY = os.environ.get('SECRET_KEY', SECRET_KEY)  # noqa: F405

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')

# Database configuration from environment
DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.mysql'),
        'NAME': os.environ.get('DB_NAME', 'dbuds'),
        'USER': os.environ.get('DB_USER', 'dbuds'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'PASSWORD'),
        'HOST': os.environ.get('DB_HOST', 'db'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'isolation_level': 'read committed',
        },
    },
    'persistent': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'persistent.sqlite3'),  # noqa: F405
        'OPTIONS': {
            'timeout': 20,
            'transaction_mode': 'IMMEDIATE',
        },
    },
}

# Use local memory cache for Docker (no memcached dependency)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'uds_response_cache',
        'OPTIONS': {
            'MAX_ENTRIES': 5000,
            'CULL_FREQUENCY': 3,
        },
    },
    'memory': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
}

# RSA Key - load from file generated by entrypoint.sh
_rsa_key_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'rsa_key.pem')
if os.path.exists(_rsa_key_file):
    with open(_rsa_key_file, 'r') as f:
        RSA_KEY = f.read()

# Proxy settings for Nginx
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# Static files
STATIC_ROOT = os.path.join(BASE_DIR, 'static')  # noqa: F405
STATIC_URL = '/uds/res/'
