[openuds]
uds-server-01 ansible_host=103.131.85.198 ansible_port=22
uds-server-02 ansible_host=103.131.85.202 ansible_port=22

[openuds_primary]
uds-server-01 ansible_host=103.131.85.198 ansible_port=22

[openuds_secondary]
uds-server-02 ansible_host=103.131.85.202 ansible_port=22

[openuds:vars]
ansible_python_interpreter=/usr/bin/python3
