---
- name: Install keepalived
  apt:
    name: keepalived
    state: present
  tags:
    - packages
    - keepalived

- name: Allow non-local bind (for VIP)
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: "1"
    sysctl_set: yes
    reload: yes
  tags:
    - system
    - keepalived
    - network

- name: Deploy keepalived config
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: restart keepalived
  tags:
    - config
    - keepalived

- name: Deploy HAProxy health check script for keepalived
  template:
    src: check_haproxy.sh.j2
    dest: /usr/local/bin/check_haproxy.sh
    owner: root
    group: root
    mode: "0755"
  notify: restart keepalived
  tags:
    - config
    - keepalived
    - haproxy

- name: Enable and start keepalived
  systemd:
    name: keepalived
    enabled: yes
    state: started
  tags:
    - service
    - keepalived
