---
- name: validate keepalived configuration
  ansible.builtin.command:
    cmd: keepalived -t -f /etc/keepalived/keepalived.conf
  changed_when: false
  listen: restart keepalived

- name: restart keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted
  listen: restart keepalived
